### ISSUE TITLE
100K files on a rpi?

### ISSUE THREAD

**Issue by meshula** [darbyjohnston/FSeq#1]
> Listing a directory with 100K files on a Raspberry Pi 3 B+

We all want to know what the heck you are up to there! I have no doubt it is awesome ;)

**Comment by darbyjohnston** [comment]
Thanks Nick! Just playing around with a small project to learn C coding and put that there to see if anyone happened to read to the bottom of the page. :) The numbers are real, though at first I was planning to benchmark with a million files but that seemed a bit silly. :)

**Comment by meshula** [comment]
haha nice, someone did :)
