### ISSUE TITLE
Can not support Chinese Folder

### ISSUE THREAD

**Issue by 0ices** [darbyjohnston/FSeq#3]

**Comment by darbyjohnston** [comment]
Hi, can you provide an example path to use for testing?

**Comment by 0ices** [comment]
Thank you for your reply.

I read the source code and noticed that it will work fine if the incoming data is converted to gbk encoding format. But I also noticed that djv cannot open the Chinese folder properly

Here is what you may need: 
D:\test\测试文件夹
D:\test\测试文件夹\大平原_1.jpg
D:\test\测试文件夹\大平原_2.jpg

**Comment by darbyjohnston** [comment]
@0ices Thanks for the example paths! I've checked in a fix for this and added the paths to the unit tests. It seems to be working OK so I'm going to close this issue, but if you notice any other problems we can reopen it or create new issues.
